service:
  gin:
    enabled: true
    mode: release
    name: ginService
    address: :9090
    prometheus:
      server:
        enabled: true
        namespace: dev_xlive
        subsystem: vod
        countsHandlingTime: true
    openTelemetry:
      enabled: true
  http:
    enabled: true
    name: httpService
    address: :9091
    prometheus:
      server:
        enabled: true
        namespace: dev_xlive
        subsystem: vod
        countsHandlingTime: true
    openTelemetry:
      enabled: true
  grpc:
    enabled: true
    name: grpcService
    address: :9092
    prometheus:
      server:
        enabled: true
        namespace: dev_xlive
        subsystem: vod
        countsHandlingTime: true
    openTelemetry:
      enabled: true
  prometheus:
    enabled: true
    name: promService
    address: :9093
    path: /metrics
  openTelemetry:
    enabled: true
    name: otelService
    namespace: dev_xlive
    service: simple
    spanExporter:
      name: jaeger
      collectorEndpoint: http://localhost:14268/api/traces
