gin:
    enabled: true
    mode: release
    name: ginService
    address: :9090
http:
    enabled: true
    name: httpService
    address: 9091
grpc:
    enabled: true
    name: grpcService
    address: :9092
    prometheus:
        enabled: true
        namespace: dev_xlive
        subsystem: vod
prometheus:
    enabled: true
    name: promService
    address: :9093
    path: /metrics