logger:
  - name: default
    level: debug
    format: text
    output: stdout

app:
  logger: default

rpcResolver:
  direct: true
  etcd: default

etcd:
  - name: default
    endpoints:
      - ${ETCD_ENDPOINT:localhost:2379}
    dialTimeout: 5s
    username: ${ETCD_USERNAME:root}
    password: ${ETCD_PASSWORD:123456}
