logger:
  - name: default
    level: info
    format: text
    output: stdout

app:
  logger: default

etcd:
  - name: default
    endpoints:
      - ${ETCD_ENDPOINT:localhost:2379}
    dialTimeout: 5s
    username: ${ETCD_USERNAME:root}
    password: ${ETCD_PASSWORD:123456}

rpcClientOptions:
  loadBalancingPolicy: round_robin
  keepalive:
    time: 30s
    timeout: 10s
    permitWithoutStream: true
